export let bootstrapOptions = {
    version: 3,
    accordionCloseOthers: true,
    accordionGroupPanelClass: 'panel-default',
    btnLoadingText: 'Loading...',
    dropdownAutoClose: 'always',
    paginationBoundaryLinks: false,
    paginationDirectionLinks: true,
    paginationFirstText: 'First',
    paginationHideSinglePage: true,
    paginationLastText: 'Last',
    paginationNextText: '>',
    paginationPreviousText: '<',
    popoverPosition: 'top',
    popoverTrigger: 'mouseover',
    tabsetType: 'tabs',
    tabsetVertical: false,
    tooltipPosition: 'top',
    tooltipTrigger: 'mouseover'
};